EMAIL_ADDRESS = "your_email@gmail.com"
EMAIL_APP_PASSWORD = "your_16_character_app_password"

NEWS_API_KEY = "your_news_api_key"

DEFAULT_STOCK = "HDFCBANK.NS"
DEFAULT_PERIOD = "1y"
DEFAULT_INTERVAL = "1d"